mysql:
  datasource:
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/count_votes?useUnicode=true&characterEncoding=utf-8
    defaultAutoCommit: true
    maxActive: 20
    maxIdle: 20
    minIdle: 1
    maxWait: 100000
server:
  port: 52388

apollo:
  bootstrap:
    enable: true
    namespaces: application
