spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/count_votes?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    defaultAutoCommit: true
    maxActive: 20
    maxIdle: 20
    minIdle: 1
    maxWait: 100000

mysql:
  datasource:
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/count_votes?useUnicode=true&characterEncoding=utf-8
    defaultAutoCommit: true
    maxActive: 20
    maxIdle: 20
    minIdle: 1
    maxWait: 100000
server:
  port: 52388
