spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://112.74.49.77:3306/count_votes?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    defaultAutoCommit: true
    maxActive: 20
    maxIdle: 20
    minIdle: 1
    maxWait: 100000

mysql:
  datasource:
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://112.74.49.77:3306/count_votes?useUnicode=true&characterEncoding=utf-8
    defaultAutoCommit: true
    maxActive: 20
    maxIdle: 20
    minIdle: 1
    maxWait: 100000
server:
  port: 52388
